import { Column, COLUMN_TYPE, FILTER_MODE } from 'src/app/shared/model/column.model';

export const TestCasesColumnsData: Column[] = [
    {
        displayName: 'Application',
        apiName: 'tec.application',
        contentName: 'application',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        searchable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select applications',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        filterAllowed: true
    },
    {
        displayName: 'Test Folder',
        apiName: 'tec.test',
        contentName: 'test',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        searchable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select test',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        filterAllowed: true
    },
    {
        displayName: 'TestCase ID',
        apiName: 'tec.testCase',
        contentName: 'testCase',
        flexGrow: 75,
        active: true,
        defaultActive: true,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Search TestCase',
        sSearch: [],
        filterDisplayed: false,
        filterAllowed: true
    },
    {
        displayName: 'Labels',
        apiName: 'lab.label',
        contentName: 'labels',
        type: COLUMN_TYPE.LABEL,
        active: true,
        defaultActive: true,
        sortable: false,
        searchable: true,
        filterDisplayed: false,
        flexGrow: 250,
        multiple: true,
        placeholder: 'Select Labels',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Description',
        apiName: 'tec.description',
        contentName: 'description',
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 250,
        defaultActive: true,
        active: true,
        filterDisplayed: false,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Search Description...',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Status',
        apiName: 'tec.status',
        contentName: 'status',
        active: true,
        defaultActive: true,
        searchable: true,
        filterDisplayed: false,
        flexGrow: 100,
        multiple: true,
        placeholder: 'Select status',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        filterAllowed: true
    },
    {
        displayName: 'Priority',
        apiName: 'tec.priority',
        contentName: 'priority',
        active: true,
        defaultActive: true,
        filterDisplayed: false,
        searchable: true,
        flexGrow: 100,
        multiple: true,
        placeholder: 'Select Priority',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        filterAllowed: true
    },
    {
        displayName: 'System',
        apiName: 'app.system',
        contentName: 'system',
        active: false,
        filterDisplayed: false,
        searchable: true,
        multiple: true,
        placeholder: 'Select System...',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Global Activation',
        apiName: 'tec.tcactive',
        contentName: 'tcActive',
        searchable: true,
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        multiple: false,
        placeholder: 'Select Gloabl Activation',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'CountryList',
        apiName: '',
        type: COLUMN_TYPE.LIST,
        contentName: 'countryList',
        flexGrow: 200,
        active: false,
        filterDisplayed: false,
        sSearch: [],
        filterAllowed: true
    },
    /****/
    {
        displayName: 'Stickers',
        apiName: 'lab.labelsSTICKER',
        contentName: 'labelsSTICKER',
        type: COLUMN_TYPE.LABEL,
        active: false,
        sortable: false,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select Stickers',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Requirements',
        apiName: 'lab.labelsREQUIREMENT',
        contentName: 'labelsREQUIREMENT',
        type: COLUMN_TYPE.LABEL,
        active: false,
        filterDisplayed: false,
        sortable: false,
        multiple: true,
        placeholder: 'Select Requirement',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Batteries',
        apiName: 'lab.labelsBATTERY',
        contentName: 'labelsBATTERY',
        type: COLUMN_TYPE.LABEL,
        active: false,
        filterDisplayed: false,
        sortable: false,
        filterAllowed: true
    },
    {
        displayName: 'QA Activation',
        apiName: 'tec.tcactive',
        contentName: 'activePROD',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterAllowed: true
    },
    {
        displayName: 'UAT Activation',
        apiName: 'tec.tcactive',
        contentName: 'activeQA',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterAllowed: true
    },
    {
        displayName: 'PROD Activation',
        apiName: 'tec.tcactive',
        contentName: 'activeUAT',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterAllowed: true
    },
    {
        displayName: 'Function',
        apiName: 'tec.function',
        contentName: 'function',
        active: false,
        filterDisplayed: false,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Function',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Project',
        apiName: 'tec.project',
        contentName: 'Project',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select Project',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Origine',
        apiName: 'tec.origine',
        contentName: 'origine',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select Origine',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Reference Origine',
        apiName: 'tec.refOrigine',
        contentName: 'refOrigin',
        active: false,
        filterDisplayed: false,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Reference Origine',
        sSearch: [],
        filterAllowed: true
    },
    {
        displayName: 'Type',
        apiName: 'tec.group',
        contentName: 'group',
        searchable: true,
        active: false,
        multiple: true,
        placeholder: 'Select Type',
        sSearch: [],
        filterDisplayed: false,
        filterAllowed: true
    },
    {
        displayName: 'Date Created',
        apiName: 'tec.dateCreated',
        contentName: 'dateCreated',
        active: false,
        filterDisplayed: false,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Date Created',
        sSearch: [],
        filterAllowed: false
    },
    {
        displayName: 'User Created',
        apiName: 'tec.usrCreated',
        contentName: 'usrCreated',
        filterDisplayed: false,
        searchable: true,
        active: false,
        multiple: true,
        placeholder: 'Select User',
        sSearch: [],
        filterAllowed: false
    },
    {
        displayName: 'TestCase Version',
        apiName: 'tec.testCaseVersion',
        contentName: 'testCaseVersion',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select TestCase Version',
        sSearch: [],
        filterAllowed: false
    },
    {
        displayName: 'Date Modification',
        apiName: 'tec.dateModif',
        contentName: 'dateModif',
        active: false,
        filterDisplayed: false,
        like: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Date Modification',
        sSearch: [],
        filterAllowed: false
    },
    {
        displayName: 'User Modification',
        apiName: 'tec.usrModif',
        contentName: 'usrModif',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select User Modification',
        sSearch: [],
        filterAllowed: false
    }];
