import { Column, COLUMN_TYPE, FILTER_MODE } from 'src/app/shared/model/front/column.model';

export const TestCasesColumnsData: Column[] = [
    {
        displayName: 'Application',
        apiName: 'tec.application',
        contentName: 'application',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select applications',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'Test Folder',
        apiName: 'tec.test',
        contentName: 'test',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select test',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'TestCase ID',
        apiName: 'tec.testCase',
        contentName: 'testCase',
        flexGrow: 75,
        active: true,
        defaultActive: true,
        filterable: true,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Search TestCase',
        sSearch: [],
        filterDisplayed: false,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'Labels',
        apiName: 'lab.label',
        contentName: 'labels',
        type: COLUMN_TYPE.LABEL,
        active: true,
        defaultActive: true,
        sortable: false,
        filterable: true,
        filterDisplayed: false,
        flexGrow: 250,
        multiple: true,
        placeholder: 'Select Labels',
        sSearch: []
    },
    {
        displayName: 'Description',
        apiName: 'tec.description',
        contentName: 'description',
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 250,
        defaultActive: true,
        active: true,
        filterDisplayed: false,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Search Description...',
        sSearch: [],
        filterable: true
    },
    {
        displayName: 'Status',
        apiName: 'tec.status',
        contentName: 'status',
        active: true,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        flexGrow: 100,
        multiple: true,
        placeholder: 'Select status',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'Priority',
        apiName: 'tec.priority',
        contentName: 'priority',
        active: true,
        defaultActive: true,
        filterDisplayed: false,
        filterable: true,
        flexGrow: 100,
        multiple: true,
        placeholder: 'Select Priority',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'System',
        apiName: 'app.system',
        contentName: 'system',
        active: false,
        filterDisplayed: false,
        filterable: true,
        multiple: true,
        placeholder: 'Select System...',
        sSearch: [],
        type: COLUMN_TYPE.LONGTEXT,
        defaultActive: false
    },
    {
        displayName: 'Global Activation',
        apiName: 'tec.tcactive',
        contentName: 'tcActive',
        filterable: true,
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        multiple: false,
        placeholder: 'Select Gloabl Activation',
        sSearch: [],
        defaultActive: false
    },
    {
        displayName: 'Countries',
        apiName: '',
        type: COLUMN_TYPE.COUNTRIES,
        contentName: 'countries',
        flexGrow: 200,
        active: false,
        filterDisplayed: false,
        sSearch: [],
        sortable: false,
        defaultActive: false,
        filterable: false
    },
    {
        displayName: 'QA Activation',
        apiName: 'tec.tcactive',
        contentName: 'activePROD',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterMode: FILTER_MODE.DROPDOWN,
        defaultActive: false,
        filterable: true
    },
    {
        displayName: 'UAT Activation',
        apiName: 'tec.tcactive',
        contentName: 'activeQA',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterMode: FILTER_MODE.DROPDOWN,
        defaultActive: false,
        filterable: true
    },
    {
        displayName: 'PROD Activation',
        apiName: 'tec.tcactive',
        contentName: 'activeUAT',
        active: false,
        filterDisplayed: false,
        type: COLUMN_TYPE.BOOLEAN,
        filterMode: FILTER_MODE.DROPDOWN,
        defaultActive: false,
        filterable: true
    },
    {
        displayName: 'Type',
        apiName: 'tec.group',
        contentName: 'group',
        filterable: true,
        active: false,
        multiple: true,
        placeholder: 'Select Type',
        sSearch: [],
        filterDisplayed: false,
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'Date Created',
        apiName: 'tec.dateCreated',
        contentName: 'dateCreated',
        active: false,
        filterDisplayed: false,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Date Created',
        sSearch: [],
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT,
        filterable: false
    },
    {
        displayName: 'User Created',
        apiName: 'tec.usrCreated',
        contentName: 'usrCreated',
        filterDisplayed: false,
        filterable: true,
        active: false,
        multiple: true,
        placeholder: 'Select User',
        sSearch: [],
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'TestCase Version',
        apiName: 'tec.testCaseVersion',
        contentName: 'testCaseVersion',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select TestCase Version',
        sSearch: [],
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT,
        filterable: false
    },
    {
        displayName: 'Date Modification',
        apiName: 'tec.dateModif',
        contentName: 'dateModif',
        active: false,
        filterable: false,
        filterDisplayed: false,
        filterMode: FILTER_MODE.SEARCH_FIELD,
        multiple: true,
        placeholder: 'Select Date Modification',
        sSearch: [],
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'User Modification',
        apiName: 'tec.usrModif',
        contentName: 'usrModif',
        filterDisplayed: false,
        active: false,
        multiple: true,
        placeholder: 'Select User Modification',
        sSearch: [],
        defaultActive: false,
        type: COLUMN_TYPE.LONGTEXT,
        filterable: true,
        filterMode: FILTER_MODE.DROPDOWN
    }];
