import { Column, COLUMN_TYPE, FILTER_MODE } from 'src/app/shared/model/front/column.model';

export const ServiceLibraryColumnsData: Column[] = [
    {
        displayName: 'Service',
        apiName: 'srv.service',
        contentName: 'service',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Select Service',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT
    },
    {
        displayName: 'Application',
        apiName: 'srv.application',
        contentName: 'application',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Application',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Type',
        apiName: 'srv.type',
        contentName: 'type',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Service Type',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT
    }, 
    {
        displayName: 'Path',
        apiName: 'servicePath',
        contentName: 'servicePath',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Service Path',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Description',
        apiName: 'srv.description',
        contentName: 'description',
        active: true,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Description',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'ServiceRequest',
        apiName: 'srv.serviceRequest',
        contentName: 'serviceRequest',
        active: false,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Service Request',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Operation',
        apiName: 'srv.operation',
        contentName: 'operation',
        active: false,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Operation',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Method',
        apiName: 'srv.method',
        contentName: 'method',
        active: false,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        multiple: true,
        placeholder: 'Method',
        sSearch: [],
        filterMode: FILTER_MODE.DROPDOWN,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Group',
        apiName: 'srv.group',
        contentName: 'group',
        active: false,
        flexGrow: 100,
        defaultActive: true,
        filterable: true,
        filterDisplayed: false,
        placeholder: 'Group',
        sSearch: [],
        filterMode: FILTER_MODE.SEARCH_FIELD,
        type: COLUMN_TYPE.LONGTEXT,
    },
    {
        displayName: 'Creation Date',
        apiName: 'srv.dateCreated',
        contentName: 'DateCreated',
        active: false,
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 100,
        defaultActive: false,
        filterable: false,
        filterDisplayed: false,
        placeholder: 'Creation date',
    },
    {
        displayName: 'Created By',
        apiName: 'srv.usrCreated',
        contentName: 'UsrCreated',
        active: false,
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 100,
        defaultActive: false,
        filterable: false,
        filterDisplayed: false,
        placeholder: 'Creation date',
    },
    {
        displayName: 'Last Updated Date',
        apiName: 'srv.dateModif',
        contentName: 'DateModif',
        active: false,
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 100,
        defaultActive: false,
        filterable: false,
        filterDisplayed: false,
        placeholder: 'Latest modification date',
    },
    {
        displayName: 'Last Updated By',
        apiName: 'srv.usrModif',
        contentName: 'UsrModif',
        active: false,
        type: COLUMN_TYPE.LONGTEXT,
        flexGrow: 100,
        defaultActive: false,
        filterable: false,
        filterDisplayed: false,
        placeholder: 'Latest modification date',
    }
];
