import { Column, COLUMN_TYPE } from 'src/app/shared/model/front/column.model';

export let CampainsColumnsData: Column[] = [
];
//     {
//         displayName: 'Test Campaign',
//         apiName: 'campaign',
//         contentName: 'campaign',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Email Notify Start',
//         apiName: 'notifyStartTagExecution',
//         contentName: 'notifyStartTagExecution',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         type: COLUMN_TYPE.BOOLEAN,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Email Notify End',
//         apiName: 'notifyEndTagExecution',
//         contentName: 'notifyEndTagExecution',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         type: COLUMN_TYPE.BOOLEAN,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Distribution List',
//         apiName: 'distribList',
//         contentName: 'distribList',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         type: COLUMN_TYPE.LONGTEXT,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Slack Notify Start',
//         apiName: 'SlackNotifyStartTagExecution',
//         contentName: 'SlackNotifyStartTagExecution',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         type: COLUMN_TYPE.BOOLEAN,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Slack Notify End',
//         apiName: 'SlackNotifyEndTagExecution',
//         contentName: 'SlackNotifyEndTagExecution',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         type: COLUMN_TYPE.BOOLEAN,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Slack Webhook URL',
//         apiName: 'SlackWebhook',
//         contentName: 'SlackWebhook',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Slack Channel',
//         apiName: 'SlackChannel',
//         contentName: 'SlackChannel',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterable: true,
//         filterDisplayed: false,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
//     {
//         displayName: 'Description',
//         apiName: 'description',
//         contentName: 'description',
//         active: true,
//         flexGrow: 100,
//         defaultActive: true,
//         filterDisplayed: false,
//         type: COLUMN_TYPE.LONGTEXT,
//         multiple: true,
//         placeholder: 'Select applications',
//         sSearch: []
//     },
// ];
